### ISSUE TITLE
Weird Mumax3 corruption problem

### ISSUE THREAD

**Issue by yliu031** [mumax/3#179]
Dear All,

I'm running Mumax 3.10 on Ubuntu 18.04 with GTX 1080 Ti (cuda9.1, v390 driver). The code works nicely over the past few weeks and I can run my previous codes fluently. But when I run a code last night (the same code as I have used before, but with larger size) Mumax suddenly got corrupted. After that Mumax becomes weird, it rarely works well and most of the time it is going to be disconnected. 

I have tried to re-install the driver, cuda, go and also the whole system. But it seems none of them works. Do you have any hints of this case?

Thank you in advance
YLiu

------------------------------------------
Below is the log output of the disconnected case:
--------------------------------------------
//mumax 3.10 linux_amd64 go1.9.6 (gc)
//CUDA 9010 GeForce GTX 1080 Ti(11175MB) cc6.1, using CC61 PTX 
//(c) Arne Vansteenkiste, Dynamat LAB, Ghent University, Belgium
//This is free software without any warranty. See license.txt
//If you use mumax in any work or publication,
//we kindly ask you to cite the references in references.bib
//no input files: starting interactive session
//output directory: mumax-2018-05-29_20h38.out/
SetGridSize(128, 64, 1)
SetCellSize(4e-9, 4e-9, 4e-9)
Msat = 1e6
Aex = 10e-12
alpha = 1
m = RandomMag()
//starting GUI at http://127.0.0.1:35367
//openend web interface in x-www-browser
//entering interactive mode
relax()
//Using cached kernel: /tmp/mumax3kernel_[128 64 1]_[0 0 0]_[4e-09 4e-09 4e-09]_6_
panic: NaN [recovered]
	panic: NaN

goroutine 1 [running, locked to thread]:
github.com/mumax/3/engine.(*guistate).EvalGUI.func1()
	/home/yliu031/go/src/github.com/mumax/3/engine/gui.go:562 +0xda
panic(0x87ef60, 0xb3c440)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/mumax/3/engine.checkNaN1(0x7fffffffe0000000)
	/home/yliu031/go/src/github.com/mumax/3/engine/util.go:199 +0x51
github.com/mumax/3/engine.GetTotalEnergy(0x3)
	/home/yliu031/go/src/github.com/mumax/3/engine/energy.go:32 +0x88
github.com/mumax/3/engine.Relax()
	/home/yliu031/go/src/github.com/mumax/3/engine/relax.go:59 +0xfa
reflect.Value.call(0x878d60, 0xaff448, 0x13, 0x92f9d9, 0x4, 0x10d73e0, 0x0, 0x0, 0x13, 0x878d60, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x878d60, 0xaff448, 0x13, 0x10d73e0, 0x0, 0x0, 0x8, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/mumax/3/script.(*call).Eval(0xc422589860, 0xc422522f80, 0xc422522f80)
	/home/yliu031/go/src/github.com/mumax/3/script/call.go:61 +0x1fe
github.com/mumax/3/script.(*BlockStmt).Eval(0xc422589830, 0x1, 0x1)
	/home/yliu031/go/src/github.com/mumax/3/script/blockstmt.go:35 +0x4d
github.com/mumax/3/engine.Eval(0x930e04, 0x7)
	/home/yliu031/go/src/github.com/mumax/3/engine/script.go:27 +0x250
github.com/mumax/3/engine.(*guistate).EvalGUI(0xf94c20, 0x930e04, 0x7)
	/home/yliu031/go/src/github.com/mumax/3/engine/gui.go:566 +0x51
github.com/mumax/3/engine.(*guistate).prepareSolver.func3.1()
	/home/yliu031/go/src/github.com/mumax/3/engine/gui.go:264 +0x3f
github.com/mumax/3/engine.(*guistate).RunInteractive(0xf94c20)
	/home/yliu031/go/src/github.com/mumax/3/engine/gui.go:67 +0xc0
github.com/mumax/3/engine.RunInteractive()
	/home/yliu031/go/src/github.com/mumax/3/engine/run.go:194 +0x2d
main.runInteractive()
	/home/yliu031/go/src/github.com/mumax/3/cmd/mumax3/main.go:82 +0x36f
main.main()
	/home/yliu031/go/src/github.com/mumax/3/cmd/mumax3/main.go:54 +0x11b

**Comment by yliu031** [comment]
I just run the default code when initializing the web interface. 
I finally figure out the reason for this problem. A small part of my GPU memory is broken, so mumax sometimes works and sometimes does not work. After replacing a new graphic card, mumax3 now works perfectly on my computer. Thanks
